create extension if not exists pgcrypto;

-- Trending topics scraped from X
create table if not exists trending_topics (
  id uuid primary key default gen_random_uuid(),
  topic_text text not null,
  scraped_at timestamptz not null default now(),
  category text,
  used_count integer not null default 0
);

create index if not exists trending_topics_scraped_at_idx on trending_topics(scraped_at desc);
create index if not exists trending_topics_topic_text_idx on trending_topics(topic_text);

-- Drafts generated by the AI, pending approval
create table if not exists drafts (
  id uuid primary key default gen_random_uuid(),
  action_type text not null check (action_type in ('original_post', 'reply', 'retweet_comment', 'mention')),
  source_tweet_url text,
  source_tweet_text text,
  source_tweet_author text,
  draft_text text not null,
  status text not null default 'pending_approval' check (status in ('pending_approval', 'approved', 'rejected', 'edited', 'expired')),
  quote_text text,
  quote_attributed_to text,
  quote_source text,
  trend_topic text,
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  rejected_at timestamptz,
  telegram_message_id bigint
);

create index if not exists drafts_status_idx on drafts(status);
create index if not exists drafts_created_at_idx on drafts(created_at desc);

-- Approved actions waiting to be executed
create table if not exists pending_actions (
  id uuid primary key default gen_random_uuid(),
  draft_id uuid not null references drafts(id) on delete cascade,
  approved_at timestamptz not null default now(),
  executed_at timestamptz,
  result text check (result in ('pending', 'success', 'failed', 'skipped_challenge')),
  error text
);

create index if not exists pending_actions_result_idx on pending_actions(result);

-- Posted content for dedup and context awareness
create table if not exists posted_content (
  id uuid primary key default gen_random_uuid(),
  text_hash text not null,
  action_type text not null check (action_type in ('original_post', 'reply', 'retweet_comment', 'mention')),
  posted_text text not null,
  posted_at timestamptz not null default now(),
  x_post_url text,
  engagement_likes integer,
  engagement_retweets integer,
  engagement_replies integer
);

create index if not exists posted_content_text_hash_idx on posted_content(text_hash);
create index if not exists posted_content_posted_at_idx on posted_content(posted_at desc);

-- Daily counters for rate limiting
create table if not exists daily_counters (
  date date primary key,
  original_post integer not null default 0,
  retweet_comment integer not null default 0,
  reply integer not null default 0,
  mention integer not null default 0
);

-- Account health log
create table if not exists account_health_log (
  id uuid primary key default gen_random_uuid(),
  date date not null,
  challenges_hit integer not null default 0,
  failures integer not null default 0,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists account_health_log_date_idx on account_health_log(date desc);

-- Verified quotes allowlist (seed manually before going live)
create table if not exists verified_quotes (
  id uuid primary key default gen_random_uuid(),
  text text not null,
  attributed_to text not null,
  source_work text not null,
  verified_by text not null,
  verified_at timestamptz not null default now(),
  notes text,
  times_used integer not null default 0,
  last_used_at timestamptz
);

create index if not exists verified_quotes_attributed_to_idx on verified_quotes(attributed_to);

-- Row Level Security: lock everything down, service_role only
alter table trending_topics enable row level security;
alter table drafts enable row level security;
alter table pending_actions enable row level security;
alter table posted_content enable row level security;
alter table daily_counters enable row level security;
alter table account_health_log enable row level security;
alter table verified_quotes enable row level security;

revoke all on table trending_topics, drafts, pending_actions, posted_content, daily_counters, account_health_log, verified_quotes from anon, authenticated;
grant all on table trending_topics, drafts, pending_actions, posted_content, daily_counters, account_health_log, verified_quotes to service_role;
